[build]
   command = "yarn build && cd functions/bookmarks && yarn install"
   publish = "public/"
   functions = "functions/"
   command = "netlify dev"

[[redirects]]
    from = "/displayLolly/*"
    to = "/displayLolly?id=:splat"